language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-arcgis-webappbuilder' ]; then cd .. && eval "mv $currentfolder generator-arcgis-webappbuilder" && cd generator-arcgis-webappbuilder; fi

